version: '3'
services:
  service-discovery:
    build: ./service-discovery
    ports:
      - 8761:8761
  cloud-gateway:
    build: ./cloud-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
    ports:
      - 9191:9191
    depends_on:
      - service-discovery
  Hystrix-Dshboard:
    build: ./Hystrix-Dshboard
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka
      ports:
        - 9195:9195
      depends_on:
        - service-discovery
