server:
  port: 9005
spring:
  profiles:
    active: house-dev
  main:
    banner-mode: off
  application:
    name: products-service

eureka:
  client:
    register-with-eureka : true
    fetch-registry: true
    serviceUrl:
      defaultZone : ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost
---
spring:
  profiles: aws
  datasource:
    url: jdbc:mysql://demo.cun2agjqacir.ap-south-1.rds.amazonaws.com:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  profiles: office
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Mypassword
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Mypassword
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  profiles: house
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---
spring:
  profiles: house-dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect